export interface LayerDef {
  id: string;
  label: string;
  source: string;
  file: string;
  type: "fill" | "line" | "circle" | "fill-extrusion" | "symbol";
  color: string;
  defaultVisible: boolean;
  group: string;
  description?: string;
  lazy?: boolean;
  labelZoom?: number;
}

export const COLON_CENTER: [number, number] = [-58.1417, -32.2292];
export const COLON_ZOOM = 13.5;

export const ZONA_COLORS: Record<string, string> = {
  "CENTRO": "#e03030",
  "URBANA": "#ff5522",
  "PERIURBANA": "#90ee10",
  "PERIURBANA-AMP SERVICIOS": "#ff9922",
  "PERIURBANA-COL HUGHES": "#ff7755",
  "QUINTAS": "#ff80df",
  "CHACRAS": "#00ffbf",
  "INDUSTRIAL": "#ffee00",
  "MIXTA COMPLEMENTO AREA INDUSTR": "#5599ff",
  "AMORTIGUACION AMBIENTAL II": "#3366ff",
  "AREA PROTEGIDA NORTE": "#22aa00",
  "AREA PROTEGIDA SUR": "#33bb11",
  "RURAL": "#cc00cc",
  "": "#888888",
};

export const LAYERS: LayerDef[] = [
  {
    id: "municipio",
    label: "Límite Municipal",
    source: "municipio",
    file: "Municipio.geojson",
    type: "line",
    color: "#60a5fa",
    defaultVisible: true,
    group: "Catastro",
    description: "Polígono del ejido municipal (Municipio.shp)",
  },
  {
    id: "seccion",
    label: "Secciones catastrales",
    source: "seccion",
    file: "seccion.geojson",
    type: "line",
    color: "#a78bfa",
    defaultVisible: false,
    group: "Catastro",
    description: "Secciones catastrales",
    labelZoom: 13,
  },
  {
    id: "grupo",
    label: "Grupos catastrales",
    source: "grupo",
    file: "grupo.geojson",
    type: "fill",
    color: "#7c3aed",
    defaultVisible: false,
    group: "Catastro",
    description: "Agrupación catastral de parcelas",
    labelZoom: 15,
  },
  {
    id: "barrios",
    label: "Barrios",
    source: "barrios",
    file: "barrios.geojson",
    type: "fill",
    color: "#3b82f6",
    defaultVisible: false,
    group: "Catastro",
    description: "Barrios y sectores urbanos",
    labelZoom: 13,
  },
  {
    id: "manzana",
    label: "Manzanas",
    source: "manzana",
    file: "manzana.geojson",
    type: "fill",
    color: "#374151",
    defaultVisible: true,
    group: "Catastro",
    description: "Manzanas del ejido urbano",
    labelZoom: 16,
  },
  {
    id: "parcela",
    label: "Parcelas",
    source: "parcela",
    file: "Parcela.geojson",
    type: "line",
    color: "#6b7280",
    defaultVisible: false,
    group: "Catastro",
    description: "División catastral de parcelas",
    lazy: true,
    labelZoom: 18,
  },
  {
    id: "superp",
    label: "Sup. construida",
    source: "superp",
    file: "SuperP.geojson",
    type: "fill",
    color: "#d97706",
    defaultVisible: false,
    group: "Catastro",
    description: "Superficie construida por parcela (SuperP.shp)",
  },
  {
    id: "calle",
    label: "Calles",
    source: "calle",
    file: "Calle.geojson",
    type: "line",
    color: "#9ca3af",
    defaultVisible: true,
    group: "Infraestructura",
    description: "Red vial urbana",
    labelZoom: 17,
  },
  {
    id: "vias",
    label: "Vías principales",
    source: "vias",
    file: "vias.geojson",
    type: "line",
    color: "#f59e0b",
    defaultVisible: false,
    group: "Infraestructura",
    description: "Vías de acceso y rutas principales",
  },
  {
    id: "bocas",
    label: "Bocas de tormenta",
    source: "bocas",
    file: "bocas.geojson",
    type: "circle",
    color: "#38bdf8",
    defaultVisible: false,
    group: "Infraestructura",
    description: "Bocas de acceso a red pluvial",
  },
  {
    id: "postes",
    label: "Postes",
    source: "postes",
    file: "postes.geojson",
    type: "circle",
    color: "#fbbf24",
    defaultVisible: false,
    group: "Infraestructura",
    description: "Postes de alumbrado y servicios",
    lazy: true,
  },
  {
    id: "hidro",
    label: "Hidrografía",
    source: "hidro",
    file: "hidro.geojson",
    type: "line",
    color: "#38bdf8",
    defaultVisible: false,
    group: "Topografía",
    description: "Cursos de agua e hidrografía",
  },
  {
    id: "cota10",
    label: "Curvas de nivel",
    source: "cota10",
    file: "c_nivel.geojson",
    type: "line",
    color: "#065f46",
    defaultVisible: false,
    group: "Topografía",
    description: "Curvas de nivel con cota altimétrica (c_nivel.shp — campo Z y COTA)",
  },
  {
    id: "edif",
    label: "Edificios (PB)",
    source: "edif",
    file: "Edif.geojson",
    type: "fill",
    color: "#6b7280",
    defaultVisible: false,
    group: "Edificios",
    description: "Edificaciones planta baja (Edif.shp)",
    lazy: true,
  },
  {
    id: "edif_palta",
    label: "Edif. Planta Alta",
    source: "edif_palta",
    file: "Edif_PAlta.geojson",
    type: "fill",
    color: "#d97706",
    defaultVisible: false,
    group: "Edificios",
    description: "Edificios de planta alta (Edif_PAlta.shp)",
  },
  {
    id: "arbol",
    label: "Arbolado urbano",
    source: "arbol",
    file: "arbol.geojson",
    type: "fill",
    color: "#22c55e",
    defaultVisible: false,
    group: "Verde urbano",
    description: "Inventario de árboles urbanos (copas) — arbol.shp",
    lazy: true,
  },
  {
    id: "zonas",
    label: "Zonificación (Ord. 130/22)",
    source: "zonas",
    file: "zonas.geojson",
    type: "fill",
    color: "#ff5522",
    defaultVisible: false,
    group: "Zonificación",
    description: "Zonas urbanas según Ordenanza 130/22",
    labelZoom: 14,
  },
];

export const LAYER_GROUPS = ["Catastro", "Infraestructura", "Topografía", "Edificios", "Verde urbano", "Zonificación"];
