export interface LayerDef {
  id: string;
  label: string;
  source: string;
  file: string;
  type: "fill" | "line" | "circle" | "fill-extrusion" | "symbol";
  color: string;
  defaultVisible: boolean;
  group: string;
  description?: string;
  lazy?: boolean;
}

export const COLON_CENTER: [number, number] = [-58.1417, -32.2292];
export const COLON_ZOOM = 13.5;

export const ZONA_COLORS: Record<string, string> = {
  "CENTRO": "#e03030",
  "URBANA": "#ff5522",
  "PERIURBANA": "#90ee10",
  "PERIURBANA-AMP SERVICIOS": "#ff9922",
  "PERIURBANA-COL HUGHES": "#ff7755",
  "QUINTAS": "#ff80df",
  "CHACRAS": "#00ffbf",
  "INDUSTRIAL": "#ffee00",
  "MIXTA COMPLEMENTO AREA INDUSTR": "#5599ff",
  "AMORTIGUACION AMBIENTAL II": "#3366ff",
  "AREA PROTEGIDA NORTE": "#22aa00",
  "AREA PROTEGIDA SUR": "#33bb11",
  "RURAL": "#cc00cc",
  "": "#888888",
};

export const LAYERS: LayerDef[] = [
  {
    id: "municipio",
    label: "Límite Municipal",
    source: "municipio",
    file: "Municipio.geojson",
    type: "line",
    color: "#60a5fa",
    defaultVisible: true,
    group: "Límites",
    description: "Polígono del ejido municipal de Colón",
  },
  {
    id: "seccion",
    label: "Secciones",
    source: "seccion",
    file: "seccion.geojson",
    type: "line",
    color: "#a78bfa",
    defaultVisible: false,
    group: "Límites",
    description: "Secciones catastrales",
  },
  {
    id: "barrios",
    label: "Barrios",
    source: "barrios",
    file: "barrios.geojson",
    type: "fill",
    color: "#3b82f6",
    defaultVisible: false,
    group: "Límites",
    description: "Barrios y sectores urbanos",
  },
  {
    id: "manzana",
    label: "Manzanas",
    source: "manzana",
    file: "manzana.geojson",
    type: "fill",
    color: "#374151",
    defaultVisible: true,
    group: "Catastro",
    description: "Manzanas del ejido urbano",
  },
  {
    id: "parcela",
    label: "Parcelas",
    source: "parcela",
    file: "Parcela.geojson",
    type: "line",
    color: "#6b7280",
    defaultVisible: false,
    group: "Catastro",
    description: "División catastral de parcelas",
    lazy: true,
  },
  {
    id: "superp",
    label: "Sup. construida",
    source: "superp",
    file: "SuperP.geojson",
    type: "fill",
    color: "#d97706",
    defaultVisible: false,
    group: "Catastro",
    description: "Superficie construida por parcela",
  },
  {
    id: "calle",
    label: "Calles",
    source: "calle",
    file: "Calle.geojson",
    type: "line",
    color: "#9ca3af",
    defaultVisible: true,
    group: "Infraestructura",
    description: "Red vial urbana",
  },
  {
    id: "bocas",
    label: "Bocas de tormenta",
    source: "bocas",
    file: "bocas.geojson",
    type: "circle",
    color: "#38bdf8",
    defaultVisible: false,
    group: "Infraestructura",
    description: "Bocas de acceso a red pluvial",
  },
  {
    id: "postes",
    label: "Postes",
    source: "postes",
    file: "postes.geojson",
    type: "circle",
    color: "#fbbf24",
    defaultVisible: false,
    group: "Infraestructura",
    description: "Postes de alumbrado y servicios",
    lazy: true,
  },
  {
    id: "cota10",
    label: "Curvas de nivel",
    source: "cota10",
    file: "cota10.geojson",
    type: "line",
    color: "#065f46",
    defaultVisible: false,
    group: "Topografía",
    description: "Curvas de nivel cada 10 metros",
  },
  {
    id: "edif",
    label: "Edificios (3D)",
    source: "edif",
    file: "Edif.geojson",
    type: "fill-extrusion",
    color: "#4b5563",
    defaultVisible: true,
    group: "Edificios",
    description: "Edificaciones generales",
    lazy: true,
  },
  {
    id: "edif_palta",
    label: "Edif. Planta Alta",
    source: "edif_palta",
    file: "Edif_PAlta.geojson",
    type: "fill-extrusion",
    color: "#b45309",
    defaultVisible: true,
    group: "Edificios",
    description: "Edificios de planta alta",
  },
  {
    id: "ph",
    label: "Techos (PH)",
    source: "ph",
    file: "ph.geojson",
    type: "fill",
    color: "#6b7280",
    defaultVisible: false,
    group: "Edificios",
    description: "Plantas de techo y cubiertas",
    lazy: true,
  },
  {
    id: "arbol",
    label: "Arbolado",
    source: "arbol",
    file: "arbol.geojson",
    type: "circle",
    color: "#16a34a",
    defaultVisible: false,
    group: "Verde urbano",
    description: "Inventario de árboles urbanos",
    lazy: true,
  },
  {
    id: "grupo",
    label: "Grupos",
    source: "grupo",
    file: "grupo.geojson",
    type: "fill",
    color: "#7c3aed",
    defaultVisible: false,
    group: "Zonificación",
    description: "Agrupación de parcelas",
  },
];

export const LAYER_GROUPS = ["Límites", "Catastro", "Infraestructura", "Topografía", "Edificios", "Verde urbano", "Zonificación"];
